In [2]:
from IPython.core.display import HTML

HTML("""
    <link rel="stylesheet" href="../fonts/cmun-bright.css">
    <style type='text/css'>
        * {
            font-family: Computer Modern Bright !important;
        }
    </style>
""")

<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [3]:
import numpy as np

# What to expect in this chapter

# 3.3 Subsetting: Indexing and Slicing

- Subsetting -- select
- Indexing -- selecting one element by index
- Slicing -- selecting a range of elements

## 3.3.1 Lists & Arrays in 1D | Subsetting & Indexing

Initializing our lists and numpy arrays to play with!

In [4]:
x = ["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
y = np.array(x)

| Syntax        | Result                         |                           | Note                                  |
|---------------|--------------------------------|---------------------------|---------------------------------------|
| `x[0]`        | First element                  | `'a1'`                    |                                       |
| `x[-1]`       | Last element                   | `'j10'`                   |                                       |
| `x[0:3]`      | Index 0 to 2                   | `['a1', 'b2', 'c3']`      | Gives $3−0=3$ elements              |
| `x[1:6]`      | Index 1 to 5                   | `['b2', 'c3', 'd4', 'e5', 'f6']` | Gives $6−1=5$ elements    |
| `x[1:6:2]`    | Index 1 to 5 in steps of 2     | `['b2', 'd4', 'f6']`      | Gives every other of $6−1=5$ elements |
| `x[5:]`       | Index 5 to the end             | `['f6', 'g7', 'h8', 'i9', 'j10']` | Gives `len(x)−5=5` elements |
| `x[:5]`       | Index 0 to 5                   | `['a1', 'b2', 'c3', 'd4', 'e5']` | Gives $5−0=5$ elements    |
| `x[5:2:-1]`   | Index 5 to 3 (i.e., in reverse) | `['f6', 'e5', 'd4']`      | Gives $5−2=3$ elements              |
| `x[::-1]`     | Reverses the list              | `['j10', 'i9', 'h8', ..., 'b2', 'a1']` |                            |

and a demo!

In [5]:
print(x[0])
print(x[-1])
print(x[0:3])
print(x[1:6])
print(x[1:6:2])
print(x[5:])
print(x[:5])
print(x[5:2:-1])
print(x[::-1])

a1
j10
['a1', 'b2', 'c3']
['b2', 'c3', 'd4', 'e5', 'f6']
['b2', 'd4', 'f6']
['f6', 'g7', 'h8', 'i9', 'j10']
['a1', 'b2', 'c3', 'd4', 'e5']
['f6', 'e5', 'd4']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']


## 3.1.2 Arrays only | Subsetting by masking

In [6]:
np_array = np.array([x for x in range(10)])
# np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])    # Notes example

We can mask an array through `False` and `True` by

In [7]:
masked_array = np_array > 3
print(masked_array)
print(np_array[masked_array])

[False False False False  True  True  True  True  True  True]
[4 5 6 7 8 9]


which returns a numpy array of Boolean values that can be used for masking! (like bitwise AND/OR index comparisons)

or in a one-liner as

In [8]:
print(np_array[np_array > 3])

[4 5 6 7 8 9]


More examples:

Bitwise inversion, AND and OR

In [9]:
print('negation')
print(np_array[~(np_array > 3)])                    # '~' means 'NOT'
print('union')
print(np_array[(np_array > 3) & (np_array < 8)])    # '&' means 'AND'
print('intersection')
print(np_array[(np_array < 3) | (np_array > 8)])    # '|' means 'OR'

negation
[0 1 2 3]
union
[4 5 6 7]
intersection
[0 1 2 9]


## 3.3.3 Lists & Arrays in 2D | Indexing & Slicing

Lists and numpy arrays have more differences when we look at N-dimensional array/lists!

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

slightly diffferent syntax although notably numpy typecasts all elements to str

In [11]:
print(py_list_2d[3])
print(np_array_2d[3])

print(py_list_2d[3][0])
print(np_array_2d[3, 0])    # Notably numpy typecasts all elements to str

print(py_list_2d[:3])
print(np_array_2d[:3])

[4, 'D']
['4' 'D']
4
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


However,

In [12]:
print(py_list_2d[:3][0])
print(np_array_2d[:3, 0])

[1, 'A']
['1' '2' '3']


Here, python list slices the first 3 elements in the top-most layer and accesses the first element in the top-most layer which is the first list `[1, 'A']`

Numpy array instead slices the first 3 elements in the top-most layer and returns an array of the first element in each element (nested list)

In [13]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 3.3.4 Growing lists

Python is super versatile in list lengths and sizes! Numpy array however, is more similar to lower level high level programming languages and is more picky with its sizes!

In [14]:
x = [1]
x += [2]
x += [3]
x += [4]
print(x)

y = [5]
y.append(6)
y.append(7)
y.append(8)
print(y)

[1, 2, 3, 4]
[5, 6, 7, 8]


It is important to note that the `.append()` method returns `None`

`.append()` and `.extend()` have very different behaviour

In [15]:
z = [1, 2, 3]
z += [4, 5, 6]
print(z)

m = [7, 8, 9]
m.extend([10, 11, 12])
print(m)

n = [13, 14, 15]
n.append([16, 17, 18])
print(n)

[1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12]
[13, 14, 15, [16, 17, 18]]


# Some loose ends

## 3..5 Tuples

Tuples

In [16]:
a = (1, 2, 3)

print(a)
print(a[0])

(1, 2, 3)
1


Tuple with one element

In [17]:
b = (0,)
print(b)

(0,)


Tuple 'arithmetic'

In [18]:
c = a + b

print(c)

(1, 2, 3, 0)


But they are IMMUTABLE!

In [19]:
a[1] = 2

TypeError: 'tuple' object does not support item assignment

## 3.3.6 Be VERY careful when copying

Conveniently, Python has the `copy` library which contains a deep copy function! Alternatively for a shallow copy, we can use the `.copy()` method available for `list`, `tuple` and some other Python datatypes! 

In [20]:
x = [1, 2, 3]
z = x.copy()
x = y

print(id(x), ": ", x)
print(id(y), ": ", y)
print(id(z), ": ", z)

4411115520 :  [5, 6, 7, 8]
4411115520 :  [5, 6, 7, 8]
4405015360 :  [1, 2, 3]


Copying a list with `.copy()` creates a shallow copy, where modifications to mutable elements in the copied `list` would also affect the original. This can lead to unintended outcomes in scenarios involving nested lists or mutable objects within the list, as changes to these elements in the copy will reflect in the original.

### An explanation... again!

Python first creates a `List` object of `[1, 2, 3]`, before assigning the address of it to `x`. `x` is a pointer to the list in memory. 

Assigning `x` to `y` results in `y` similarly becoming a pointer to the same list in memory. 

Here's `deepCopy()` again!

In [21]:
def deepCopyR(obj, memo=None):
    if memo is None:
        memo = {}

    obj_id = id(obj)

    if obj_id in memo:      # If object is already copied, return it to avoid cyclic references
        return memo[obj_id]

    if isinstance(obj, dict):       # Dictionaries
        copied_dict = {}
        memo[obj_id] = copied_dict  # Add to memo to handle cyclic references
        for key, value in obj.items():
            copied_dict[deepCopyR(key, memo)] = deepCopyR(value, memo)
        return copied_dict

    elif isinstance(obj, list):     # Lists
        copied_list = []
        memo[obj_id] = copied_list  # Add to memo to handle cyclic references
        for item in obj:
            copied_list.append(deepCopyR(item, memo))
        return copied_list

    elif hasattr(obj, "__dict__"):      # User-defined classes
        copied_obj = obj.__class__()    # Create a new instance of the object's class
        memo[obj_id] = copied_obj       # Add to memo to handle cyclic references
        for key, value in obj.__dict__.items():
            setattr(copied_obj, key, deepCopyR(value, memo))
        return copied_obj

    else:           # If it's a primitive type or immutable, return as is
        return obj

list0 = [1, 2, [3, 5], 4]
print("list0 ID: ", id(list0), "Value: ", list0)

list1 = list0
print("list1 ID: ", id(list1), "Value: ", list1)

list2 = list0.copy()
list3 = deepCopyR(list0)

list0[2][0] = 6

print("list2 ID: ", id(list2), "Value: ", list2)
print("list3 ID: ", id(list3), "Value: ", list3)

list0 ID:  4404987520 Value:  [1, 2, [3, 5], 4]
list1 ID:  4404987520 Value:  [1, 2, [3, 5], 4]
list2 ID:  4404991552 Value:  [1, 2, [6, 5], 4]
list3 ID:  4409898240 Value:  [1, 2, [3, 5], 4]


# Exercises & Self-Assessment

A fun exercise using several lists

In [22]:
def bresenhams_line_algorithm(x0, y0, x1, y1):
    """
        Generate points of a line from (x0,y0) to (x1,y1) using Bresenham's algorithm.
    """
    points = []
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx + dy

    while True:
        points.append((x0, y0))
        if x0 == x1 and y0 == y1:
            break
        e2 = 2 * err
        
        if e2 >= dy:    # Horizontal step
            err += dy
            x0 += sx
        
        if e2 <= dx:    # Vertical step
            err += dx
            y0 += sy

    return np.array(points)

def plot_line_ascii(points, width=20, height=10):
    """
        Plot the line represented by 'points' on a grid of size 'width' x 'height' using ASCII art.
    """
    grid = [['·' for _ in range(width)] for _ in range(height)]
    for x, y in points:
        if 0 <= x < width and 0 <= y < height:
            grid[y][x] = '+'
    
    for row in reversed(grid):
        print(' '.join(row))

x0, y0 = 3, 8   # Start
x1, y1 = 7, 2  # End 
line_points = bresenhams_line_algorithm(x0, y0, x1, y1)

plot_line_ascii(line_points)


· · · · · · · · · · · · · · · · · · · ·
· · · + · · · · · · · · · · · · · · · ·
· · · · + · · · · · · · · · · · · · · ·
· · · · + · · · · · · · · · · · · · · ·
· · · · · + · · · · · · · · · · · · · ·
· · · · · · + · · · · · · · · · · · · ·
· · · · · · + · · · · · · · · · · · · ·
· · · · · · · + · · · · · · · · · · · ·
· · · · · · · · · · · · · · · · · · · ·
· · · · · · · · · · · · · · · · · · · ·


# Footnotes
Referenced [Storing Data (Good)](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/2_storing-data_good.html)